name: Build and Publish CachyOS NVIDIA Kmod RPM Image

on:
  schedule:
    - cron: '0 0 1 */2 *'     # every 2 months
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-akmods-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install Fedora tools (dnf + rpm)
      - name: Install DNF and RPM
        run: |
          sudo apt-get update
          sudo apt-get install -y dnf rpm curl

      # Enable rpmfusion + CachyOS COPR repos
      - name: Configure Fedora Repos
        run: |
          sudo dnf install -y \
            https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-43.noarch.rpm \
            https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-43.noarch.rpm
          sudo curl -Lo /etc/yum.repos.d/copr-bieszczaders-kernel-cachyos.repo \
            https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos/repo/fedora-43/bieszczaders-kernel-cachyos-fedora-43.repo

      - name: Build NVIDIA akmods
        run: |
          set -euxo pipefail
          mkdir -p rpms/kmods
          sudo dnf -y install kernel-cachyos kernel-cachyos-devel-matched \
              akmod-nvidia gcc gcc-c++ make elfutils-libelf-devel rpm-build akmods
          KVER=$(rpm -q --qf "%{VERSION}-%{RELEASE}.%{ARCH}\n" kernel-cachyos | head -n1)
          sudo akmods --force --kernels "$KVER" --akmod nvidia
          sudo find /var/cache/akmods/nvidia/ -name "*.rpm" -exec cp {} rpms/kmods/ \;

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-cachyos-nvidia-kmods
          path: rpms/kmods/

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Container Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/kernel-cachyos-nvidia:latest
