name: Build and Publish CachyOS Kernel RPM Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-kernel-image:
    runs-on: ubuntu-22.04
    container: fedora:43
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          dnf -y update
          dnf -y install rpm-build dnf-plugins-core spectool curl gcc make bc \
            bison flex elfutils-devel dwarves zstd python3 python3-pyyaml \
            openssl-devel git

      - name: Build kernel RPMs
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-cachyos-nvidia-rpms
          path: rpms/kernel/

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Container Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/kernel-cachyos-nvidia:latest
