name: Build NVIDIA RPM Container

on:
  repository_dispatch:
    types: [build-image]

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download kmods RPM artifacts
        uses: actions/download-artifact@v4
        with:
          name: rpms
          path: rpms/kmods

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/kernel-cachyos-nvidia:latest
