name: Build CachyOS NVIDIA Kmods

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */2 *'  # every 2 months

permissions:
  contents: write       # needed for repository_dispatch
  id-token: write       # optional for signing

jobs:
  build-kmods:
    runs-on: ubuntu-latest
    container:
      image: fedora:43
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable CachyOS COPR and RPM Fusion repos
        run: |
          dnf -y upgrade
          dnf -y install dnf-plugins-core curl
          # CachyOS kernel repo
          dnf config-manager --add-repo https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos/repo/fedora-43/bieszczaders-kernel-cachyos.repo
          # RPM Fusion
          curl -Lo rpmfusion-free-release.rpm https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-43.noarch.rpm
          curl -Lo rpmfusion-nonfree-release.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-43.noarch.rpm
          dnf -y install rpmfusion-free-release.rpm rpmfusion-nonfree-release.rpm

      - name: Install build dependencies
        run: |
          dnf -y install akmod-nvidia kernel-cachyos kernel-cachyos-devel-matched

      - name: Build NVIDIA kmods
        run: |
          mkdir -p rpms/kmods
          KVER=$(rpm -q --qf "%{VERSION}-%{RELEASE}.%{ARCH}\n" kernel-cachyos | head -n1)
          akmods --force --kernels "$KVER" --akmod nvidia
          find /var/cache/akmods/nvidia/ -name "*.rpm" -exec cp {} rpms/kmods/ \;

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rpms
          path: rpms/kmods/

  dispatch-image:
    needs: build-kmods
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Container Build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: build-image
