name: Build and Publish CachyOS Kernel NVIDIA RPM Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:             # ✅ Needed for GHCR and checkout
  contents: read         # To clone the repo
  packages: write        # To push the container to GHCR
  id-token: write        # Optional, useful for cosign signing later

jobs:
  build-akmods-image:
    runs-on: ubuntu-22.04
    container: fedora:43      # ✅ Run inside a Fedora container so dnf is available
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          dnf -y update
          dnf -y install \
            rpm-build \
            dnf-plugins-core \
            spectool \
            git \
            curl \
            make \
            gcc \
            kernel-devel \
            fedpkg \
            rpmdevtools

      - name: Build RPMs
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-cachyos-nvidia-open-rpms
          path: rpms/

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Container Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/kernel-cachyos-nvidia:latest
