name: Build CachyOS NVIDIA RPM Image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download kmod RPM artifacts
        uses: actions/download-artifact@v4
        with:
          name: rpms
          path: rpms/kmods

      - name: Determine kernel version from RPM
        id: kernel-version
        run: |
          KVER=$(rpm -qp --qf "%{VERSION}-%{RELEASE}.%{ARCH}" rpms/kmods/*.rpm | head -n1)
          echo "Kernel version: $KVER"
          echo "KVER=$KVER" >> $GITHUB_ENV
          echo "KVER=$KVER" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Container Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/kernel-cachyos-nvidia:${{ steps.kernel-version.outputs.KVER }}
