name: Build NVIDIA Kmods Container Image

on:
  repository_dispatch:
    types: [build-image]

permissions:
  contents: read
  packages: write  # needed to push to GHCR
  id-token: write

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download RPM Artifacts
        uses: actions/download-artifact@v4
        with:
          name: rpms
          path: rpms/kmods/

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Container Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/kernel-cachyos-nvidia:latest
