name: Build CachyOS NVIDIA Kmods & Package into Immutable Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */2 *'  # every 2 months

permissions:
  contents: write       # needed for repository_dispatch
  id-token: write       # optional for signing

jobs:
  build-kmods:
    runs-on: ubuntu-latest
    container:
      image: fedora:43
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable CachyOS COPR and RPM Fusion repos
        run: |
          dnf -y upgrade
          dnf -y install dnf-plugins-core curl
          # CachyOS kernel repo
          sudo dnf -y copr enable bieszczaders/kernel-cachyos
          # RPM Fusion
          dnf -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-43.noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-43.noarch.rpm

      - name: Install build dependencies
        run: |
          dnf -y install akmod-nvidia kernel-cachyos kernel-cachyos-devel-matched

      - name: Build NVIDIA kmods
        run: |
          mkdir -p rpms/kmods
          KVER=$(rpm -q --qf "%{VERSION}-%{RELEASE}.%{ARCH}\n" kernel-cachyos | head -n1)
          akmods --force --kernels "$KVER" --akmod nvidia
          find /var/cache/akmods/nvidia/ -name "*.rpm" -exec cp {} rpms/kmods/ \;

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rpms
          path: rpms/kmods/
  
  build-image:
    needs: build-kmods
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download kmods RPM artifacts
        uses: actions/download-artifact@v5
        with:
          name: rpms
          path: rpms/kmods

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/kernel-cachyos-nvidia:latest
